sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - src
script:
  - make generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: src
  local-dir: public
